{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "provider.fullname" . }}
  namespace: {{ include "provider.namespace" . }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "provider.selectorLabels" . | nindent 6 }}
{{- end }}
