apiVersion: v2
name: provider
description: Monobase Provider App - React/Vite frontend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - frontend
  - react
  - vite
  - provider
home: https://github.com/monobaselabs/monobase-infra
sources:
  - https://github.com/monobaselabs/monobase
maintainers:
  - name: Monobase
    email: hello@monobase.com
